### PR TITLE
Gdi tooltip

### PR DESCRIPTION
**Pull request by esunder**
Added full color support and moved GdiTooltip functionality to new file.
image

Allows the use to enable GDI rendering of tooltips:
image

User can enable/disable GDI rendering and can change the transparency of the window and text separately:
image

### CODE REVIEW

**Comment by esunder** [comment]
Fixed a small bug that causes the window to sometimes clear while rendering. Instead of hiding the window when rendering an empty string, we will just return, leaving any rendered window visible. The only call to hide the window now is from the timer.

Example of bug (now fixed):
image

**Comment by esunder** [comment]
@Eruyome The "bug fix" above is not a solid fix. It will fix the issue when the background is not transparent, but it is ultimately just rendering the window on top of the other window. Because of this, it causes another issue where if you lookup the same item again without moving the mouse to hide the price list, you will see the "requesting search results..." message on top of the price list. I am still trying to fix it, but I have some questions: 

1. Why does the macro sometimes call ShowTooltip("") immediately followed by ShowTooltip(someString)? Why not just call ShowTooltip(someString)?
e.g. after parsing the trade data:
`ShowToolTip("")`
`ShowToolTip(ParsedData)`

2. Why does the ItemInfo macro call ToolTip, Font.SetFixedFont, and then ToolTip again? It seems redundant to call ToolTip twice here. You can tell in my pull request for GDI, I only call GdiTooltip once.
e.g. in the ShowToolTip function
`ToolTip, %String%, XCoord, YCoord`
`Fonts.SetFixedFont()`
`ToolTip, %String%, XCoord, YCoord`

I am getting strange behavior where it appears that the ShowTooltip("") executes AFTER ShowTooltip(someVariable) and this causes the price list to not render, there is a small square with border in its place. You can see it flicker in this gif before the price list shows up.
https://puu.sh/xQgBj/950f23a407.gif

**Comment by Eruyome** [comment]
1. Sometimes the tooltip lost it's selected font, falling back to the default. I never really found out why but showing an empty tooltip fixed it for good.

2. Not sure right now, ItemInfo was developed by a bunch of people over a long period of time so some things may not be optimal and I don't know everything withoug digging deeper into the code.

I may have to test your code and play around with it to give you any answer on that weird square, haven't had the time yet.
There is no async code involved in the item search -  tooltip rendering.

**Comment by esunder** [comment]
Ok, well I have pushed a change that will basically ignore empty strings in GdiTooltip. This seems to resolve the issue, but will not allow pattern 1 from my previous comment to clear/show tooltip. You can just call ShowTooltip(someString) and it will work. Let me know if you find any other issues with the testing.

**Pull request merged**
