### PR TITLE
Adding GDI support for ItemInfo

### PR DESCRIPTION
**Pull request by esunder**
Allows the use to enable GDI rendering of tooltips:
image

User can enable/disable GDI rendering and can change the transparency of the window and text separately:
image

### CODE REVIEW

**Comment by Eruyome** [comment]
Huh, I wanted to do that for a while, just thought it would be a bit more work than that.
Nice work.
Will take a look after getting some other things done.

**Comment by Eruyome** [comment]
It has to be added to the beta branch though, which may require some changes.

**Comment by esunder** [comment]
Ok, thanks. Let me know if you need anything else.

**Comment by Eruyome** [comment]
If you're bored you could add options for text-, border- and background color. But I can do that myself also later.

**Comment by dein0s** [comment]
Maybe move this code from monstrous and monolithic `POE-ItemInfo.ahk` into some external file/lib?
Just sneaking around :)

**Comment by esunder** [comment]
Both good suggestions. I will add them and push the changes. Might take me a day or so. I only have occasional evenings free during the week.

**Comment by esunder** [comment]
Moving to a new PR against beta branch

**Pull request closed without merging**
