### PR TITLE
user settings script rework

### PR DESCRIPTION
**Pull request by Eruyome**

### CODE REVIEW

**Comment by Eruyome** [comment]
@aRTy42 
I made this PR to have a better look at the changes I made so far because I could use some help in form of discussion.

I always wanted to use a user folder to keep/save the config files instead of saving them in the project folder. With my current code this would be possible. The script copies the config files and a default_AdditionalMacros.txt to the user folder while making sure to only copy and overwrite those files when needed by comparing hashes (saved in a file at time of copying). This way the user can change those files without triggering an overwrite. Only changes in the resource folders are triggering this (differences between script versions). Overwritten files are backed up and the user can be notified.

So far those files aren't used by the script, haven't changed that part yet, they are just wasting space there.

While this should work in general it could also cause issues when someone uses multiple versions of the script (switching versions for some reason or developing). So I'm not sure how to continue from here. Maybe there are more problems I can't think of right now.

- Just use this as is?
- Let the script write it's path to the registry ("installing it", without any version number) and use the configs only for the script located in that path while using local/portable files for every other script location? This would require some kind of user interaction to confirm/deny this installation or manually execute it. This would also make it easier to make an auto-installer by deleting the contents of that directory and extracting the latest release-zip at that location. Could also require 2 release versions (easy with my release-script), one "installer" and one portable, just some added file with a flag.
- Don't use it at all.
- Some other solution.

**Comment by aRTy42** [comment]
Use as is. Currently everyone has to fiddle around with the macros on every release, so if this improves the usability for most people while devs and special cases don't have it worse than before, I see no reason not to use it. Registry/install path does not fully solve multiple versions (I think) or at least makes the whole topic more complicated again for the majority of users, so I'd rather not go there.

**Comment by Eruyome** [comment]
I think adding some kind of flag for development purposes would be nice (still use the local configs), just have to think about that implementation since those functions are executed before the ini files are being read, so simply using debug mode won't work. 

Registry path would require some more work:
- At script start check if the path is set
- If yes and the current running script is in a different path ask the user if he wants to "install" the script to the set path or run in "portable" mode
- If no, "install" it after asking for a path
- other steps/things

With enough work this shouldn't be complicated for users, hopefully... I'm not really sure about all those registry keys needed though.

**Comment by aRTy42** [comment]
I think more options or confirmation popups or the like won't make it fail safe in the end, it probably rather opens up more possibilities for some configuration to behave unintended or for bugs in general.

In particular when developing a new version and reloading the script rather often, there shouldn't be another thing to deal with.

**Comment by Eruyome** [comment]
It would certainly make room for possible issues. Maybe just using it as is plus the following could be a solution:

- Add a "download" option to the update notification.
- Open a File/Folder select dialog to select an "install path" (default = current script dir)
- Download the latest release, extract it to the specified folder, either creating it or overwriting the entire directory, maybe backing up the directory to make sure you can't delete important stuff.
- Run the downloaded script.

Would be the best compromise I can think of right now, being the most user friendly while having the least  potential to cause issues and having an auto updater.

And if I really want to I could check the script dir for .git folder/files to decide if it's a dev version or not and handle the usersettings stuff differently, maybe creating a sub-folder/different project folder to have at least a production and a dev version. could even use the current selected branch to create sub folders. `.git\HEAD` has that info easily available.

**Comment by aRTy42** [comment]
That sounds good.

The only slight issue I see there is that people will no longer visit the GitHub page and thus will even more likely skip reading update notes. Currently only the notes of the latest release are displayed by the script, unless I overlooked something there. If the user misses a big release and then downloads a few days later when there is a small follow-up already, warnings like "UPDATE AUTOHOTKEY!" get lost more easily.

**Comment by Eruyome** [comment]
We could always improve the update notification, add the option to show more update notes ("show more" => last X), add a button to open the update note files or even force a URL open after update completion to visit the github releases page. Not sure about the best solution but there are options.

**Comment by aRTy42** [comment]
The download process you described is great, in case the comment sounded too negative.

Does it seem feasible and sensible to you to display all update notes between the currently used and newest version?

**Comment by Eruyome** [comment]
Considering that the update check downloads this https://api.github.com/repos/PoE-TradeMacro/PoE-TradeMacro/releases it shouldn't be a problem.

**Comment by Eruyome** [comment]
Now that I replaced the config paths (without much testing yet) I have the problem that includes can't have variable/dynamic paths, so AdditionalMacros.txt is a problem.

`#Include,  %userDirectory%\AdditionalMacros.txt` won't work
`#Include,  AdditionalMacros.txt` is wrong

Worst case is that I would have to merge that file with the other scripts (what I'm already doing for TradeMacro with a few files), but then I would have to add this to ItemInfo also. Maybe there are other solutions.

**Comment by aRTy42** [comment]
According to [this](https://autohotkey.com/docs/commands/_Include.htm) the variable "%A_AppData%" is working for include.

**Comment by Eruyome** [comment]
Hm, that's true, I could change from MyDocuments to AppData, that wouldn't make it possible to add your own scripts though (not that bad). It also woudln't be possible to use a dev version for this file using the current branch name used by git (also not that bad since we don't develop there anyway normally).

**Comment by aRTy42** [comment]
I misread it though, I thought of MyDocuments when reading the example. The current location seems way nicer than some ...AppData/Roaming path. Unless it is a pain for you to work with, I'd rather stick to MyDocuments.

**Comment by Eruyome** [comment]
Not sure if its a pain siince I already added a menu entry to open that directory.

`#Include, i* %A_AppData%\AdditionalMacros.txt`
Could do this to try to include it (if it exists), but I can't use conditional includes also, so what do I do when it doesn't exist? Currently all that checking and copying is done in the same script, after the preprocessing.

**Comment by Eruyome** [comment]
Made same bigger changes.

- Moved ItemInfo.ahk to resources\ahk\
- Added a run/merge script for it and changed the TradeMacro run/merge scripts
- All those scripts set userDirectory and projectName, handle the user settings stuff (create and copy folders/files, compare hashes etc)
- userDirectory and projectName are passed as arguments to the merged script so ItemInfo and TradeMacro work both independently and together.
- AdditionalMacros also is merged with those scripts and this can be improved to make a user folder and merge all contained scripts.

**Comment by Eruyome** [comment]
I also implemented the script updater. It's not entirely finished since I have to move parts of that code to a temporary script outside of the project folder to actually overwrite the folder were the script is running from and then executing the macro again. Should be easy by passing some parameters to that other script.

I believe that the entire update process is very save/stable/robust. There shoudl be more than enough checks and prompts to not overwrite unwanted files/folders and development versions are also considered (default install path has `_devVersion` appended).

**Comment by Eruyome** [comment]
I'm done with the updater if there are no issues, currently there is some debug code in `PoEScripts_FinishUpdate`, you may need this if you want the automatic script restart after the update to work. I believe I had some issues because the code downloaded from github it too old.

**Comment by Eruyome** [comment]
Please try to take a moment and test all this stuff, if you can get it work without problems I'll make a beta release and ask on reddit for testers.

**Comment by aRTy42** [comment]
Downloaded your branch. Using the two Run_... ahk files works fine. I guess you are aware that the "reload macro" function on the rightclick menu causes problems (such as not finding the config/AdditionalMacros files) because the script relies on being started by the merger.

All ItemInfo functionalities seem fine. The Ctrl+D function of the TradeMacro returns "No item found." despite reading the item correctly. Ctrl+W and Q are also fine. Might be a cookie issue, but I'm not familiar with it and the 1.7.3-beta version still works fine.

Looking at the UpdateScript() code does not help at all, I've never done anything like this, so I have no idea what kind of errors to expect or to look for. I won't spot something that you missed that way. If you have a suggestion how I can test the function, please tell me.

**Comment by Eruyome** [comment]
Well, there are 2 way to test it in general.
- use the mentioned debug mode and copy the projectfolder to somewhere else, that way you will replace the current script with the same files instead of using the latest github release.
- just use it normally, of course the script restart won't work because of different file names that aren't changed in the latest release yet.

Doing this observe what happens, folders being created, files being copied and so on. Try adding more debug output. But in general I want from you to be just another user and confirm that everyhting works for you. And regarding the update function, just look at the logic behind it, am I doing things too complicated? Could things be more convenient for the user? Is something not save enough, for example should there be more checks if files/folders exist or do I need to be even more careful when moving/deleting files and directories? Stuff like that. I haven't written any update myself so far, aside from this one.

**Comment by Eruyome** [comment]
That "no ites found" stuff is really interesting... the downloaded html is fine, currency search works, too.
Then this happens (nothing was changed here) and all variabled are empty:

```
TBody       := TradeUtils.StrX( html,   "<tbody id=""item-container-" . %A_Index%,  N,0,  "</tbody>", 1,23, N )
AccountName := TradeUtils.StrX( TBody,  "data-seller=""",                           1,13, """"  ,     1,1,  T )
Buyout      := TradeUtils.StrX( TBody,  "data-buyout=""",                           T,13, """"  ,     1,1,  T )
IGN         := TradeUtils.StrX( TBody,  "data-ign=""",                              T,10, """"  ,     1,1     )
```

Have to look further into that...

**Comment by Eruyome** [comment]
Man, I'm fucking tired right now. I'm doing some rubberduck debugging here because I don't get what the problem is.

- The first broken commit didn't change any directly related code as far as I can see. https://github.com/PoE-TradeMacro/POE-TradeMacro/commit/f5ed38c549fc94bdcaff72ad96b72ba26c721d71
- We have four functions to parse the HTML
  * `TradeFunc_ParseHtml()`, `TradeFunc_GetMeanMedianPrice()`, `TradeFunc_ParseCurrencyHtml()` and `TradeFunc_ParseAlternativeCurrencySearch()`
- These two can be considered as relevant:
  * `TradeFunc_ParseHtml()` since they are not only working very similiar but also the latter works as intended `TradeFunc_ParseCurrencyHtml()`  

___
**Some code comparisons.**
Both functions enter those loops, both loops run the set amount of 15 times and the `html` variable contains the successfully downloaded and correct html. Opening the html in a browser displays the search results with more than enough items.

Assumption (not tested yet): Since older versions still work and this code here wasn't changed we don't have any poe.trade html changes messing with our parsing.

Both functions use the unchanged `TradeUtils.StrX()`, in the case of `TradeFunc_ParseHtml()`  it simply returns an empty string.
___

**`TradeFunc_ParseHtml()`** :

```
While A_Index <= NoOfItemsToCount {
		TBody         := TradeUtils.StrX( html,   "<tbody id=""item-container-" . %A_Index%,  N, 0, "</tbody>" , 1,23, N )

                console.log(A_Index " -> "  TBody)
```

**`TradeFunc_ParseCurrencyHtml()`** :

```
While A_Index < NoOfItemsToShow {
		Offer       := TradeUtils.StrX( html,   "data-username=""",     N, 0, "Contact Seller"   , 1,1, N )

                console.log(A_Index " -> "  TBody)
```

___

Some more debug code to put before the loops:
```
RegExMatch(html, "i)id=""search-results-first""(.*)", searchResults)
html := searchResults1
```

> (Above is optional)

```
FileDelete, %A_ScriptDir%\test.html
FileAppend, %html%, %A_ScriptDir%\test.html
console.clear()
```

___

So, **W T F** ? Sometimes I hate programming. Is it so obvious that I just don't see it? Or is it really that weird?

**Comment by aRTy42** [comment]
The commit you linked changes A_MyDocuments to A_AppData in the two ahk files resources/ahk/POE-ItemInfo.ahk and resources/ahk/TradeMacroInit.ahk. You changed that to global variables in a later commit.

**Comment by Eruyome** [comment]
I know, but I have 2 practically identical functions, one works, the other doesn't. They have the same arguments, use different html (but fetched the same way). This parsing code doesn't depend on any configs at all:

```
FileRead, html, %A_ScriptDir%\test.txt
While A_Index < NoOfItemsToShow {
		TBody       := TradeUtils.StrX( html,   "<tbody id=""item-container-" %A_Index%,  N,0,  "</tbody>", 1,1, N )
		AccountName := TradeUtils.StrX( TBody,  "data-seller=""",                           1,13, """"  ,     1,1,  T )
		Buyout      := TradeUtils.StrX( TBody,  "data-buyout=""",                           T,13, """"  ,     1,1,  T )
		IGN         := TradeUtils.StrX( TBody,  "data-ign=""",                              T,10, """"  ,     1,1     )

		console.log(A_Index " -> " AccountName " : " TBody)
```
The right html is there.  
I even manually saved a search result page from the browser to read it right before the parsing loop.

**Comment by aRTy42** [comment]
I don't see any mistakes or missing checks in the UpdateScript() function. Using the update button worked fine when using the defaults. Changing them brings up some issues.

In the folder selection dialog:
 * If you create a new folder "Custom Name", this folder will be created, the script downloaded and extracted to another newly created folder "Custom". The updater will then attempt to launch "...\Custom\Name.ahk" which obviously fails.
 * Just typing a folder name into the folder field instead of using the "new folder" button should probably also try to create that folder. Currently it uses that name if the folder exists, but it simply uses the previous name/selection if the typed in name does not exist.

---

Again in the folder selection dialog, the line
`want to install/extract" project " to`
is missing a space after extract.

I also think that "promt" in the following line is not a verb. Speaking of overwriting files and then explaining that we actually back them up is also a bit odd, how about:
```"Selecting an existing folder will ask for confirmation and back up that folder, as for example 'MyFolder_backup'.`n"```

**Comment by Eruyome** [comment]
Man, still no idea why that function doesn't work anymore for 2 parsing functions but still works for one. Anyway, made a simple replacement for it and it works again, not sure if it's a bit slower though.

**Comment by Eruyome** [comment]
Fixed the issues with spaces in paths, it seems you have to be careful with that when passing arguments to other scripts, makes sense.

https://autohotkey.com/docs/commands/FileSelectFolder.htm I removed the edit field for now, I don't like it but I don't see any way to read the user input.

> If the user types an invalid folder name in the edit field, OutputVar will be set to the folder selected in the navigation tree rather than what the user entered, at least on Windows XP.

___

Changed the text according to your suggestions.

**Comment by Eruyome** [comment]
I'm running out of ideas of what I can add/fix for a beta release. Tomorrow is probably not a bad idea to publish it. Got anything to add here http://pastebin.com/88H8ZFyF? @aRTy42

**Comment by aRTy42** [comment]
Nothing to add, the text looks fine. (necessary with one c by the way)

**Comment by Eruyome** [comment]
Yeah, I often make that mistake and it always look odd to me...

**Comment by Eruyome** [comment]
Thought of some things to implement before releasing a beta:

- Making sure that the install dir is not protected/system folder, for example `C:\Windows\`
- Making sure that the install dir is not a drive root, for example `C:\`

- Adding an option/setting to skip the folder selection on an update. (always instsall in current script dir)
  * Sub-option to skip making a backup of the install dir.

**Comment by aRTy42** [comment]
Sounds reasonable.

**Comment by Eruyome** [comment]
Done. Could make a beta release but it's probably better when you take a quick look/test at what I've done. And maybe I'm improving my release script to also create a draft on github including asset upload. But since this need authentication I may not do it.

**Comment by Eruyome** [comment]
https://www.reddit.com/r/pathofexile/comments/5ut7sl/tool_poetrademacro_200_beta_autoupdater_global/

**Comment by Eruyome** [comment]
I set the merged scripts to hidden now, that should cause less incentive to use them to start the macro.

**Pull request merged**
