### PR TITLE
Fix issues related to non-ENG keyboard layouts

### PR DESCRIPTION
**Pull request by dein0s**
Added `ConvertKeyToKeyCode.ahk` which allows to convert key to SC/VK (depending on the needs).
Wrapped all necessary keys that I've able to found with `KeyToSC()` function.

### CODE REVIEW

**Comment by dein0s** [comment]
Actually I'm thinking about adding sc/vk checkbox into the general group also. Because it seems to me that virtual keys are more universal then scan codes. Also they act properly regarding to `NumLock` state and other stuff. `CustomGetKeyCode()` is already here to suit this needs.

**Comment by dein0s** [comment]
Well, not sure that I can fit it into the GUI properly. @Eruyome can you take care of this on a spare time?

**Comment by Eruyome** [comment]
Does is make sense to add this as an option? Without having read up on that, what are advantages/disadvantages of using one option instead of the other? 
Leaving such technical choices up to the user can be a bad idea.

**Comment by dein0s** [comment]
I'd say it's not that necessary, but might be useful in some very rare cases. While I agree that it can be a bad idea, there also should be an easy solution for endpoint user to switch between this options without touching actual code. Maybe only option in config without gui checkbox?

Some cases off the top of my head:
- a key was already remapped (by ahk, regedit, or any other software), which is done by remapping virtual keys. Scan codes comes very handy in here.
- as it was mentioned above, virtual keys can act properly regarding to the `NumLock` state and other modifications, and fires only action key, rather then hardware key. `NumPad0` and `NumpadEnd` will have the same scan code (hardware key), but different virtual keys.

**Comment by dein0s** [comment]
Done with this.
Any thoughts? (Except my Atom fixed some whitespaces :D)

**Comment by Eruyome** [comment]
Was a bit busy with doing nothing and sleeping and stuff so I only read your descriptions so far, but it seems nice. Will take a better look soon :p

**Comment by Eruyome** [comment]
Changed the bases around a bitsince I had to delete devEru for a moment.

**Comment by dein0s** [comment]
**NB:**
- move `ConvertKeyToKeyCode.ahk` into `lib` folder;
- make changes after https://github.com/PoE-TradeMacro/POE-TradeMacro/pull/514 (additional macros keys, config)

**Pull request merged**
