### PR TITLE
Fixed pseudo calculation #224

### PR DESCRIPTION
**Pull request by 4GForce**
This fixes the pseudo calculations and will be a lot more easier to maintain.
There still could be unhandled cases but its not like they were handled before.

### CODE REVIEW

**Comment by 4GForce** [comment]
I already have 2 minor fixes and some more improvement that i'll commit tomorrow

**Comment by Eruyome** [comment]
Ok, I'll just wait a bit until you're ready. There are still issues though (commented on the github issue).

**Comment by Eruyome** [comment]
Btw, I invited you as a collaborator so that you can clone the repo on work directly on it instead of your own fork of the repo. Please start working directly on the repo and push your cahgnes to some presonal development branch. It's far easier to work on that together and test it that way, I can simply checkout your branch to take a look at it.

**Comment by 4GForce** [comment]
Ok, my bad, you can cancel this pull request ... I created a new branch directly on your repo and I'm working from there now.

**Pull request closed without merging**
