### PR TITLE
Fix 'increased Attack Damage' to be a prefix

### PR DESCRIPTION
**Pull request by Irfy**
Now from a feature branch. Sorry for the mess.

### CODE REVIEW

**Comment by aRTy42** [comment]
For Eru: This fix is already merged at ItemInfo, not sure if you want to also merge it here.

**Comment by Eruyome** [comment]
Then I'll just close it and merge ItemInfo later.

**Comment by Irfy** [comment]
Just a reminder as the new league starts: this is still not fixed.

**Comment by aRTy42** [comment]
Do you have a recent version? The line the pull request was about is fixed. If there is still an error is comes from something else.

**Comment by Irfy** [comment]
My bad. Forgot `--all` with git fetch :) Sorry for confusion.

**Pull request closed without merging**
